#Azure DevOps pipeline to deploy AWS resources via Terraform
#Siphiwe

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: TerraformInstaller@0
  inputs:
    terraformVersion: '0.12.3'
- task: TerraformTaskV2@2
  inputs:
    provider: 'aws'
    command: 'init'
    backendServiceAWS: 'firco-aws-tf'
    backendAWSBucketName: 'firco-tfstate-bucket'
    backendAWSKey: 'fircotf'

- task: TerraformTaskV2@2
  inputs:
    provider: 'aws'
    command: 'plan'
    environmentServiceNameAWS: 'firco-aws-tf'

- task: TerraformTaskV2@2
  inputs:
    provider: 'aws'
    command: 'apply'
    environmentServiceNameAWS: 'firco-aws-tf'

